# Generated by Django 5.0.1 on 2024-02-12 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('resale', 'Resale'), ('pg', 'PG'), ('on_lease', 'On Lease')], max_length=50, unique=True),
        ),
    ]
