# Generated by Django 5.0.1 on 2024-02-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0005_built_land'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='p_type',
            field=models.CharField(choices=[('land', 'Land'), ('built', 'Built')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='property',
        ),
    ]
