# Generated by Django 5.0.1 on 2024-02-12 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0006_category_p_type_delete_property'),
    ]

    operations = [
        migrations.AddField(
            model_name='built',
            name='p_type',
            field=models.CharField(default='Built', max_length=10),
        ),
        migrations.AddField(
            model_name='built',
            name='to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bricks.category'),
        ),
        migrations.AddField(
            model_name='land',
            name='EMI',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='land',
            name='EMI_rate',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='land_type',
            field=models.CharField(choices=[('agg', 'Aggrecultural'), ('res', 'Residential')], default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='p_type',
            field=models.CharField(default='Land', max_length=10),
        ),
        migrations.AddField(
            model_name='land',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='land',
            name='to',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bricks.category'),
        ),
        migrations.AlterField(
            model_name='category',
            name='p_type',
            field=models.CharField(choices=[('land', 'Land'), ('built', 'Built')], max_length=20),
        ),
        migrations.AlterField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('pg', 'PG'), ('on_lease', 'On Lease')], max_length=50),
        ),
        migrations.AlterField(
            model_name='land',
            name='area',
            field=models.IntegerField(default=0),
        ),
    ]
