# Generated by Django 5.0.1 on 2024-02-12 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0007_built_p_type_built_to_land_emi_land_emi_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='built',
            name='to',
        ),
        migrations.RemoveField(
            model_name='land',
            name='to',
        ),
        migrations.AddField(
            model_name='built',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('pg', 'PG'), ('on_lease', 'On Lease')], default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='type',
            field=models.CharField(choices=[('rent', 'Rent'), ('sale', 'Sale'), ('pg', 'PG'), ('on_lease', 'On Lease')], default=None, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='category',
        ),
    ]
