# Generated by Django 5.0.1 on 2024-02-13 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0008_remove_built_to_remove_land_to_built_type_land_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='built',
            name='address',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='land',
            name='address',
            field=models.CharField(default=None, max_length=200, unique=True),
        ),
    ]
