# Generated by Django 5.0.1 on 2024-02-13 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0009_alter_built_address_alter_land_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='built',
            old_name='images',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='land',
            name='EMI',
        ),
        migrations.RemoveField(
            model_name='land',
            name='EMI_rate',
        ),
    ]
