# Generated by Django 5.0.1 on 2024-02-13 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0010_rename_images_built_image_remove_land_emi_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='built',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='built',
            old_name='fs',
            new_name='furnished_status',
        ),
    ]
