# Generated by Django 5.0.1 on 2024-02-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0012_alter_built_furnished_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='built',
            name='furnished_status',
            field=models.CharField(choices=[('F', 'Furnished'), ('uf', 'Un-Furnished')], max_length=50, null=True),
        ),
    ]
