# Generated by Django 5.0.1 on 2024-02-14 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0014_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='built',
            name='cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bricks.category'),
        ),
        migrations.AddField(
            model_name='land',
            name='cat',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='bricks.category'),
        ),
    ]
