# Generated by Django 5.0.1 on 2024-02-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0016_remove_built_type_remove_land_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='built',
            name='image',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='images',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
