# Generated by Django 5.0.1 on 2024-02-14 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0018_alter_built_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='built',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='land',
            name='images',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
