# Generated by Django 5.0.1 on 2024-02-15 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0020_remove_built_rent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='built',
            name='faces',
            field=models.CharField(choices=[('East', 'east'), ('North-East', 'North-East'), ('North', 'north'), ('North-West', 'North-West'), ('West', 'west'), ('South-West', 'South-West'), ('South', 'south'), ('South-East', 'South-East')], max_length=50),
        ),
        migrations.AlterField(
            model_name='built',
            name='furnished_status',
            field=models.CharField(choices=[('Furnished', 'Furnished'), ('Un-Furnished', 'Un-Furnished')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='built',
            name='status',
            field=models.CharField(choices=[('Under Construction', 'Under Construction'), ('Ready To Move', 'Reasy to move')], max_length=50),
        ),
        migrations.AlterField(
            model_name='built',
            name='type_of_ownership',
            field=models.CharField(choices=[('Independent', 'Independent'), ('With Owner', 'With Owner')], max_length=50),
        ),
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.CharField(choices=[('Aggricultural', 'Aggrecultural'), ('Residential', 'Residential')], default=None, max_length=50, null=True),
        ),
    ]
