# Generated by Django 5.0.1 on 2024-02-15 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0021_alter_built_faces_alter_built_furnished_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='built',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
