# Generated by Django 5.0.1 on 2024-02-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0022_built_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='built',
            old_name='image',
            new_name='images',
        ),
    ]
