# Generated by Django 5.0.1 on 2024-02-20 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0023_rename_image_built_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='built',
            name='name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
