# Generated by Django 5.0.2 on 2024-02-22 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0024_built_name_land_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='built',
            name='owner_name',
            field=models.CharField(default=None, max_length=500, null=True),
        ),
    ]
