# Generated by Django 5.0.2 on 2024-02-22 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0025_built_owner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='built',
            name='owner_phone',
            field=models.IntegerField(null=True),
        ),
    ]
