# Generated by Django 5.0.2 on 2024-02-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0027_land_owner_name_land_owner_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='built',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='land',
            old_name='images',
            new_name='image',
        ),
    ]
