# Generated by Django 5.0.2 on 2024-02-25 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0028_rename_images_built_image_rename_images_land_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='built',
            name='owner_mail',
            field=models.EmailField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='land',
            name='owner_mail',
            field=models.EmailField(max_length=500, null=True),
        ),
    ]
