# Generated by Django 5.0.2 on 2024-02-25 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bricks', '0029_built_owner_mail_land_owner_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='land',
            name='land_type',
            field=models.CharField(choices=[('Aggricultural', 'Aggrecultural'), ('Residential', 'Residential'), ('Industrial', 'Industrial')], default=None, max_length=50, null=True),
        ),
    ]
